name: sheets_backend
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  platform: ^3.1.0
  cupertino_icons: ^1.0.2
  gsheets: ^0.4.2
  intl: ^0.18.0
  splashscreen: ^1.3.5
  file_picker: ^4.1.6
  iconsax: ^0.0.8
  dio: ^4.0.6
  dotted_border: ^2.0.0+3
  firebase_auth: ^4.2.2
  path_provider: ^2.0.12
  flutter_secure_storage: ^7.0.1
  google_sign_in: ^5.4.4
  # firebase_auth:  
  # google_sign_in:   
  # flutter_secure_storage: 
  # path_provider:  
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/home_bg.png
    - assets/images/bottom_bg.png
    - assets/images/landing.png
    - assets/images/bottom_bg_1.png
    - assets/images/mark.png
    - assets/images/logo.png

